apiVersion: v1
kind: Pod
metadata:
  name: workflow-launcher-ms
  labels:
    app: workflow-launcher-ms
spec:
  nodeName: minikube
  containers:
  - name: microservice-workflow-launcher
    # get latest version of image
    image: lucasjellema/microservice-workflow-launcher:1
    ports:
    # containerPort is the port exposed by the container (where nodejs express api is listening)
    - containerPort: 8098
    lifecycle:
      postStart:
        exec:
          # add ubuntu to hosts file
          # command: ["cat","192.168.188.101","ubuntu",">","/etc/hosts"]
          command: ["sh","-c","echo 192.168.188.101 ubuntu > /etc/hosts"]
    volumeMounts:
    - mountPath: /var/log/nginx
      name: nginx-logs
  volumes:
  - name: nginx-logs
    emptyDir: {}